version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: myapp-node-server
    volumes:
      - ./server:/usr/src/app
    ports:
      - "4000:4000"
    networks:
      - myapp-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: myapp-react-client
    volumes:
      - ./client:/usr/app
    ports:
      - "3000:3000"
    networks:
      - myapp-network

networks:
  myapp-network:

